import type { Metadata } from 'next'
import { Inter, Poppins, } from 'next/font/google'
import './globals.css'
import {GameControlContextProvider} from '@/contexts/gamecontrol/Provider'
import React from "react";

const poppins = Poppins(
  {
    subsets: ['latin'],
    variable: '--font-poppins',
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  }
)

export const metadata: Metadata = {
  title: '?ERFECT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans bg-black300 flex justify-center`}>
        <GameControlContextProvider>
          {children}
        </GameControlContextProvider>
      </body>
    </html>
  )
}
