export const tempData =
  [
    "AFC Bournemouth",
    "Arsenal",
    "Aston Villa",
    "Brentford",
    "Brighton & Hove Albion",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Liverpool",
    "Luton Town",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sheffield United",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton Wanderers",
    "Birmingham City",
    "Blackburn Rovers",
    "Bristol City",
    "Cardiff City",
    "Coventry City",
    "Huddersfield Town",
    "Hull City",
    "Ipswich Town",
    "Leeds United",
    "Leicester City",
    "Middlesbrough",
    "Millwall",
    "Norwich City",
    "Plymouth Argyle",
    "Preston North End",
    "Queens Park Rangers",
    "Rotherham United",
    "Sheffield Wednesday",
    "Southampton",
    "Stoke City",
    "Sunderland",
    "Swansea City",
    "Watford",
    "West Bromwich Albion",
    "Portsmouth",
    "Oxford United",
    "Bolton Wanderers",
    "Peterborough United",
    "Barnsley",
    "Stevenage",
    "Blackpool",
    "Lincoln City",
    "Derby County",
    "Wycombe Wanderers",
    "Burton Albion",
    "Leyton Orient",
    "Bristol Rovers",
    "Cambridge United",
    "Charlton Athletic",
    "Port Vale",
    "Exeter City",
    "Shrewsbury Town",
    "Wigan Athletic",
    "Northampton Town",
    "Carlisle United",
    "Fleetwood Town",
    "Cheltenham Town",
    "Reading",
    "Accrington Stanley",
    "AFC Wimbledon",
    "Barrow",
    "Stockport County",
    "Notts County",
    "Wrexham",
    "Mansfield Town",
    "Crew Alexandra",
    "Morecambe",
    "Gillingham",
    "Swindon Town",
    "Milton Keynes Dons",
    "Salford City",
    "Crawley Town",
    "Walsall",
    "Bradford City",
    "Doncaster Rovers",
    "Harrogate Town",
    "Newport County",
    "Colchester United",
    "Grimbsy Town",
    "Forest Green Rovers",
    "Tranmere Rovers",
    "Sutton United",
    "Celtic",
    "Rangers",
    "Aberdeen",
    "Hibernian",
    "Heart of Midlothian",
    "Dundee",
    "St Mirren",
    "Kilmarnock",
    "Motherwell",
    "Livingston",
    "Ross County",
    "St Johnstone",
    "Nice",
    "Paris Saint-Germain",
    "Monaco",
    "Lille",
    "Reims",
    "Brest",
    "Nantes",
    "Rennes",
    "Marseille",
    "Lens",
    "Montpellier",
    "Lyon",
    "Strasbourg",
    "Metz",
    "Toulouse",
    "Le Havre",
    "Lorient",
    "Clermont",
    "Inter Milan",
    "Juventus",
    "AC Milan",
    "Atalanta",
    "Napoli",
    "Fiorentina",
    "Lazio",
    "Bologna",
    "Roma",
    "Monza",
    "Lecce",
    "Frosinone",
    "Torino",
    "Genoa",
    "Sassuolo",
    "Hellas Verona",
    "Udinese",
    "Empoli",
    "Cagliari",
    "Salernitana",
    "Bayer 04 Leverkusen",
    "Bayern Munich",
    "VFB Stuttgart",
    "Borussia Dortmund",
    "Borussia Monchengladbach",
    "RB Leipzig",
    "1899 Hoffenheim",
    "Eintracht Frankfurt",
    "SC Freiburg",
    "Vfl Wolfsburg",
    "FC Augsburg",
    "Werder Bremen",
    "1 FC Heidenheim 1846",
    "Darmstadt 98",
    "1 FC Union Berlin",
    "Vfl Bochum 1848",
    "1 FC Koln",
    "Mainz 05",
    "Real Madrid",
    "Girona",
    "Barcelona",
    "Atletico Madrid",
    "Real Sociedad",
    "Athletic Bilbao",
    "Real Betis",
    "Valencia",
    "Rayo Vallecano",
    "Sevilla",
    "Las Palmas",
    "Osauna",
    "Villarreal",
    "Getafe",
    "Cadiz",
    "Mallorca",
    "Alaves",
    "Celta Viga",
    "Granada",
    "Almeria",
  ];
