export const tempData =
  [
    "AFC Bournemouth",
    "Arsenal",
    "Aston Villa",
    "Brentford",
    "Brighton & Hove Albion",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Liverpool",
    "Luton Town",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sheffield United",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolverhampton Wanderers",
    "Birmingham City",
    "Blackburn Rovers",
    "Bristol City",
    "Cardiff City",
    "Coventry City",
    "Huddersfield Town",
    "Hull City",
    "Ipswich Town",
    "Leeds United",
    "Leicester City",
    "Middlesbrough",
    "Millwall",
    "Norwich City",
    "Plymouth Argyle",
    "Preston North End",
    "Queens Park Rangers",
    "Rotherham United",
    "Sheffield Wednesday",
    "Southampton",
    "Stoke City",
    "Sunderland",
    "Swansea City",
    "Watford",
    "West Bromwich Albion",
    "Portsmouth",
    "Oxford United",
    "Bolton Wanderers",
    "Peterborough United",
    "Barnsley",
    "Stevenage",
    "Blackpool",
    "Lincoln City",
    "Derby County",
    "Wycombe Wanderers",
    "Burton Albion",
    "Leyton Orient",
    "Bristol Rovers",
    "Cambridge United",
    "Charlton Athletic",
    "Port Vale",
    "Exeter City",
    "Shrewsbury Town",
    "Wigan Athletic",
    "Northampton Town",
    "Carlisle United",
    "Fleetwood Town",
    "Cheltenham Town",
    "Reading",
    "Accrington Stanley",
    "AFC Wimbledon",
    "Barrow",
    "Stockport County",
    "Notts County",
    "Wrexham",
    "Mansfield Town",
    "Crew Alexandra",
    "Morecambe",
    "Gillingham",
    "Swindon Town",
    "Milton Keynes Dons",
    "Salford City",
    "Crawley Town",
    "Walsall",
    "Bradford City",
    "Doncaster Rovers",
    "Harrogate Town",
    "Newport County",
    "Colchester United",
    "Grimbsy Town",
    "Forest Green Rovers",
    "Tranmere Rovers",
    "Sutton United",
    "Celtic",
    "Rangers",
    "Aberdeen",
    "Hibernian",
    "Heart of Midlothian",
    "Dundee",
    "St Mirren",
    "Kilmarnock",
    "Motherwell",
    "Livingston",
    "Ross County",
    "St Johnstone",
    "Nice",
    "Paris Saint-Germain",
    "Monaco",
    "Lille",
    "Reims",
    "Brest",
    "Nantes",
    "Rennes",
    "Marseille",
    "Lens",
    "Montpellier",
    "Lyon",
    "Strasbourg",
    "Metz",
    "Toulouse",
    "Le Havre",
    "Lorient",
    "Clermont",
    "Inter Milan",
    "Juventus",
    "AC Milan",
    "Atalanta",
    "Napoli",
    "Fiorentina",
    "Lazio",
    "Bologna",
    "Roma",
    "Monza",
    "Lecce",
    "Frosinone",
    "Torino",
    "Genoa",
    "Sassuolo",
    "Hellas Verona",
    "Udinese",
    "Empoli",
    "Cagliari",
    "Salernitana",
    "Bayer 04 Leverkusen",
    "Bayern Munich",
    "VFB Stuttgart",
    "Borussia Dortmund",
    "Borussia Monchengladbach",
    "RB Leipzig",
    "1899 Hoffenheim",
    "Eintracht Frankfurt",
    "SC Freiburg",
    "Vfl Wolfsburg",
    "FC Augsburg",
    "Werder Bremen",
    "1 FC Heidenheim 1846",
    "Darmstadt 98",
    "1 FC Union Berlin",
    "Vfl Bochum 1848",
    "1 FC Koln",
    "Mainz 05",
    "Real Madrid",
    "Girona",
    "Barcelona",
    "Atletico Madrid",
    "Real Sociedad",
    "Athletic Bilbao",
    "Real Betis",
    "Valencia",
    "Rayo Vallecano",
    "Sevilla",
    "Las Palmas",
    "Osasuna",
    "Villarreal",
    "Getafe",
    "Cadiz",
    "Mallorca",
    "Alaves",
    "Celta Vigo",
    "Granada",
    "Almeria",
    "Chesterfield",
    "Barnet",
    "Bromley",
    "Solihull Moors",
    "Altrincham",
    "FC Halifax Town",
    "Aldershot Town",
    "Gateshead",
    "Rochdale",
    "Oldham Athletic",
    "Eastleigh",
    "Woking",
    "Dagenham & Redbridge",
    "Hartlepool United",
    "Southend United",
    "Dorking Wanderers",
    "Wealdstone",
    "Boreham Wood",
    "Ebbsfleet United",
    "AFC Fylde",
    "Maidenhead United",
    "York City",
    "Oxford City",
    "Kidderminster Harriers",
    "FC Cincinnati",
    "Orlando City SC",
    "Columbus Crew",
    "Philadelphia Union",
    "New England Revolution",
    "Atlanta United",
    "Nashville SC",
    "New York City FC",
    "New York Red Bulls",
    "Toronto FC",
    "Chicago Fire",
    "DC United",
    "Inter Miami CF",
    "Charlotte FC",
    "CF Montreal",
    "St Louis City SC",
    "Seattle Sounders FC",
    "Los Angeles Football Club",
    "Houston Dynamo",
    "Real Salt Lake",
    "Vancouver Whitecaps FC",
    "FC Dallas",
    "Sporting Kansas City",
    "San Jose Earthquakes",
    "Portland Timbers",
    "Minnesota United FC",
    "Colorado Rapids",
    "Austin FC",
    "LA Galaxy",
  ];
let longestWordInEntireArray = "";
const bigResult = tempData.reduce((acc, curr) => {
    let longestOfAnIndividualTeam = "";
   const result = curr.split(" ").reduce((acc2, curr2) => {
       if (curr2.length > longestOfAnIndividualTeam.length) {
          longestOfAnIndividualTeam = curr2;
       }
     return longestOfAnIndividualTeam;
    }, "");
    if (result.length > longestWordInEntireArray.length) {
        longestWordInEntireArray = result;
    }
    return longestWordInEntireArray;
}, "");


console.log(bigResult, bigResult.length);

export const keyboardContent = [
  ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
  ["-","Z", "X", "C", "V", "B", "N", "M", "&"],
  ["ENTER", "SPACE", "DEL"],
];

export interface Keymap {
    id: number;
    row: number;
    key: string;
    isIncorrectGuess?: boolean;
}

export const extendedKeyboardContent: Array<Array<Keymap>> = [
  [
    { id: 1, key: "1", isIncorrectGuess: false, row: 0 },
    { id: 2, key: "2", isIncorrectGuess: false, row: 0 },
    { id: 3, key: "3", isIncorrectGuess: false, row: 0 },
    { id: 4, key: "4", isIncorrectGuess: false, row: 0 },
    { id: 5, key: "5", isIncorrectGuess: false, row: 0 },
    { id: 6, key: "6", isIncorrectGuess: false, row: 0 },
    { id: 7, key: "7", isIncorrectGuess: false, row: 0 },
    { id: 8, key: "8", isIncorrectGuess: false, row: 0 },
    { id: 9, key: "9", isIncorrectGuess: false, row: 0 },
    { id: 10, key: "0", isIncorrectGuess: false, row: 0 },
  ],
  [
    { id: 11, key: "Q", isIncorrectGuess: false, row: 1 },
    { id: 12, key: "W", isIncorrectGuess: false, row: 1 },
    { id: 13, key: "E", isIncorrectGuess: false, row: 1 },
    { id: 14, key: "R", isIncorrectGuess: false, row: 1 },
    { id: 15, key: "T", isIncorrectGuess: false, row: 1 },
    { id: 16, key: "Y", isIncorrectGuess: false, row: 1 },
    { id: 17, key: "U", isIncorrectGuess: false, row: 1 },
    { id: 18, key: "I", isIncorrectGuess: false, row: 1 },
    { id: 19, key: "O", isIncorrectGuess: false, row: 1 },
    { id: 20, key: "P", isIncorrectGuess: false, row: 1 },
  ],
  [
    { id: 21, key: "A", isIncorrectGuess: false, row: 2 },
    { id: 22, key: "S", isIncorrectGuess: false, row: 2 },
    { id: 23, key: "D", isIncorrectGuess: false, row: 2 },
    { id: 24, key: "F", isIncorrectGuess: false, row: 2 },
    { id: 25, key: "G", isIncorrectGuess: false, row: 2 },
    { id: 26, key: "H", isIncorrectGuess: false, row: 2 },
    { id: 27, key: "J", isIncorrectGuess: false, row: 2 },
    { id: 28, key: "K", isIncorrectGuess: false, row: 2 },
    { id: 29, key: "L", isIncorrectGuess: false, row: 2 },
  ],
  [
    { id: 30, key: "-", isIncorrectGuess: false, row: 3 },
    { id: 31, key: "Z", isIncorrectGuess: false, row: 3 },
    { id: 32, key: "X", isIncorrectGuess: false, row: 3 },
    { id: 33, key: "C", isIncorrectGuess: false, row: 3 },
    { id: 34, key: "V", isIncorrectGuess: false, row: 3 },
    { id: 35, key: "B", isIncorrectGuess: false, row: 3 },
    { id: 36, key: "N", isIncorrectGuess: false, row: 3 },
    { id: 37, key: "M", isIncorrectGuess: false, row: 3 },
    { id: 38, key: "&", isIncorrectGuess: false, row: 3 },
  ],
  [
    { id: 39, key: "ENTER", row: 4},
    { id: 40, key: "SPACE", row: 4},
    { id: 41, key: "DEL", row: 4},
  ]
];
